name = "bedrinth"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = ".open-next/worker.js"

r2_buckets = []
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[images]
binding = "IMAGES"
[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "bedrinth"
